{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_pty",
    "module": "flutter_pty_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_pty_profile-1.0.aar",
          "url": "flutter_pty_profile-1.0.aar",
          "size": 28648,
          "sha512": "61d81c22ee9d9c07bc7944c5b987c48f7144a8aaf33641da3b8401ae2a2ec19186a03691a0cdcc3dd5f6c2d518abe30708af8a07788411812c626108a0b9509a",
          "sha256": "bf7f6b69254a2c607a0a2418a28f4f3f4809b17123ebd10ac63a3f4eb5cadd14",
          "sha1": "b372d67fab87dd5333bc212319cf8618ad020bd1",
          "md5": "dce20ef3b151c305278e210b427ff268"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_pty_profile-1.0.aar",
          "url": "flutter_pty_profile-1.0.aar",
          "size": 28648,
          "sha512": "61d81c22ee9d9c07bc7944c5b987c48f7144a8aaf33641da3b8401ae2a2ec19186a03691a0cdcc3dd5f6c2d518abe30708af8a07788411812c626108a0b9509a",
          "sha256": "bf7f6b69254a2c607a0a2418a28f4f3f4809b17123ebd10ac63a3f4eb5cadd14",
          "sha1": "b372d67fab87dd5333bc212319cf8618ad020bd1",
          "md5": "dce20ef3b151c305278e210b427ff268"
        }
      ]
    }
  ]
}
