{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 12840,
          "sha512": "d336b3b342c88417f21a87b1815e0971cc06214fc7944424c8c4e2ca4f576948dd0492bee016980298f9a0347454452d244bfaaf58f9cd13d1585164fe47a461",
          "sha256": "4e93afc5b9eedeade8ca0060bae73437dce3d4a468934a6b7152e1f909f3e611",
          "sha1": "38e0f55868fb79696e023d895a564061a240e9d8",
          "md5": "874ed244edbdb0f60adbcdd5ea5b4c08"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 12840,
          "sha512": "d336b3b342c88417f21a87b1815e0971cc06214fc7944424c8c4e2ca4f576948dd0492bee016980298f9a0347454452d244bfaaf58f9cd13d1585164fe47a461",
          "sha256": "4e93afc5b9eedeade8ca0060bae73437dce3d4a468934a6b7152e1f909f3e611",
          "sha1": "38e0f55868fb79696e023d895a564061a240e9d8",
          "md5": "874ed244edbdb0f60adbcdd5ea5b4c08"
        }
      ]
    }
  ]
}
