{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.aar",
          "url": "webview_flutter_android_profile-1.0.aar",
          "size": 136839,
          "sha512": "c522d41a95466a4b43e21a86829484c765164f41ad67f9bf7bf5ee67ad4cc424795d7a26f7d63efeb83cc785b266a0aadcc5a751dd076e69f624638bd59c9f3c",
          "sha256": "f117fd1efb8202a604266617b43047f2dbe1da71312936547a2431ffba5fcbf2",
          "sha1": "27e5e8cdd3ce654c72d5b1b1de8742727680f6d0",
          "md5": "a33c5734e073767067c5d58a0d13fe0e"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.aar",
          "url": "webview_flutter_android_profile-1.0.aar",
          "size": 136839,
          "sha512": "c522d41a95466a4b43e21a86829484c765164f41ad67f9bf7bf5ee67ad4cc424795d7a26f7d63efeb83cc785b266a0aadcc5a751dd076e69f624638bd59c9f3c",
          "sha256": "f117fd1efb8202a604266617b43047f2dbe1da71312936547a2431ffba5fcbf2",
          "sha1": "27e5e8cdd3ce654c72d5b1b1de8742727680f6d0",
          "md5": "a33c5734e073767067c5d58a0d13fe0e"
        }
      ]
    }
  ]
}
