{
  "formatVersion": "1.1",
  "component": {
    "group": "io.material.plugins.dynamic_color",
    "module": "dynamic_color_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic_color_release-1.0.aar",
          "url": "dynamic_color_release-1.0.aar",
          "size": 5867,
          "sha512": "3da053da10dad62c5869a60fd1e2b4d277079b2e241a89c3d25624ff0e0937d74865456b5dd98524bb9e65c695abe25d2d60003a984ee4f74944581fcde3ecdb",
          "sha256": "4746f25fd75750975592b26bc3effc98414950351a0deadf8e155fb364e7f51c",
          "sha1": "fe819083cfd42b15e23f9d433ce93980a7325b4b",
          "md5": "a712ac61359b04c5a14009c2e132eaf3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic_color_release-1.0.aar",
          "url": "dynamic_color_release-1.0.aar",
          "size": 5867,
          "sha512": "3da053da10dad62c5869a60fd1e2b4d277079b2e241a89c3d25624ff0e0937d74865456b5dd98524bb9e65c695abe25d2d60003a984ee4f74944581fcde3ecdb",
          "sha256": "4746f25fd75750975592b26bc3effc98414950351a0deadf8e155fb364e7f51c",
          "sha1": "fe819083cfd42b15e23f9d433ce93980a7325b4b",
          "md5": "a712ac61359b04c5a14009c2e132eaf3"
        }
      ]
    }
  ]
}
