{
  "formatVersion": "1.1",
  "component": {
    "group": "com.idlefish.flutterboost",
    "module": "flutter_boost_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_boost_profile-1.0.aar",
          "url": "flutter_boost_profile-1.0.aar",
          "size": 83548,
          "sha512": "65e15979a80ce9890d9f16b9db4e2f49ed351de73ec82d819d91e4b14af8f846b6ea1f7f07514c01bd82911fc245df16b5fe5a6561464aa93dbafaca597cf2d9",
          "sha256": "48364f8b545e4cc925d1360f700cf10320af3ced283c9a383f003c8a31773c71",
          "sha1": "e1e87bee9cddb26e066521681529eb1d55d4d44d",
          "md5": "90b39bd3590ea0f54d4e187631133d66"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_boost_profile-1.0.aar",
          "url": "flutter_boost_profile-1.0.aar",
          "size": 83548,
          "sha512": "65e15979a80ce9890d9f16b9db4e2f49ed351de73ec82d819d91e4b14af8f846b6ea1f7f07514c01bd82911fc245df16b5fe5a6561464aa93dbafaca597cf2d9",
          "sha256": "48364f8b545e4cc925d1360f700cf10320af3ced283c9a383f003c8a31773c71",
          "sha1": "e1e87bee9cddb26e066521681529eb1d55d4d44d",
          "md5": "90b39bd3590ea0f54d4e187631133d66"
        }
      ]
    }
  ]
}
