{
  "formatVersion": "1.1",
  "component": {
    "group": "com.idlefish.flutterboost",
    "module": "flutter_boost_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_boost_release-1.0.aar",
          "url": "flutter_boost_release-1.0.aar",
          "size": 83551,
          "sha512": "5b6a1e7060454250719236a3f2a6d2998ceb7038f8bd2a19a84701293ea482b5e0abb52df87c5ccbc60d5a95997d2b303735f52a65604ade73fcde44af22eebf",
          "sha256": "93aee9b67b9e8ffaf1c4de37e70f9e9e9b901c7cd529e28dd499d4b39fe6d0de",
          "sha1": "066339fcbbc75d90e272c6959152ef79afefdda5",
          "md5": "a3f80c1d3438be930ac199dc445113b1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_boost_release-1.0.aar",
          "url": "flutter_boost_release-1.0.aar",
          "size": 83551,
          "sha512": "5b6a1e7060454250719236a3f2a6d2998ceb7038f8bd2a19a84701293ea482b5e0abb52df87c5ccbc60d5a95997d2b303735f52a65604ade73fcde44af22eebf",
          "sha256": "93aee9b67b9e8ffaf1c4de37e70f9e9e9b901c7cd529e28dd499d4b39fe6d0de",
          "sha1": "066339fcbbc75d90e272c6959152ef79afefdda5",
          "md5": "a3f80c1d3438be930ac199dc445113b1"
        }
      ]
    }
  ]
}
